branch-defaults:
  default:
    environment: udagram-app-dev-1
environment-defaults:
  udagram-app-dev-1:
    branch: null
    repository: null
global:
  application_name: udagram-app
  default_ec2_keyname: uda-key-pair
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
